---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{ namespace }}
  name: kube-event-metric-exporter
  namespace: {{ namespace }}
spec:
  image: {{ image }}
  env:
  - name: "METRICS_ADDRESS"
    value: "0.0.0.0:8080"
  port: 8080
  prometheus:
    enabled: true
    path: /
    port: "8080"
  replicas:
    max: 1
    min: 1
