# vi: se et:

name: Build and deploy image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images
jobs:
  build_push_sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@main
        id: image
        with:
          name: kube-event-metric-exporter
          dockerfile: ./Dockerfile
          google_service_account: gh-kube-event-analyzer
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      version: ${{ steps.image.outputs.version }}
  rollout:
    permissions:
      id-token: write
    name: Deploy to NAIS
    needs: ["build_push_sign"]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: nais/deploy/actions/deploy@v1
      env:
        CLUSTER: prod-gcp
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        RESOURCE: nais.yaml
        PRINT_PAYLOAD: "true"
        VAR: image=europe-north1-docker.pkg.dev/nais-io/nais/images/kube-event-metric-exporter:${{ needs.build_push_sign.outputs.version }},namespace=nais
